server:
  port: 8090

spring:
  application:
    name: config
  profiles:
    acctice:
      - native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka
#11-14 discovery service yi bulabilmesi ve kendini kaydetmesi icindir. 8097 de calisiyor eurekayi burdan bulacak
